////----GENERIC BULLET---/////

#define CG_RUBBERBULLET_DAMAGE 5

///---HANDGUN AMMO---///

#define CG_46CAL_DAMAGE 25

#define CG_9MM_DAMAGE 30
#define CG_9MM_HV_DAMAGE 35

#define CG_45ACP_DAMAGE 35
#define CG_45ACP_HP_DAMAGE 40

#define CG_44MAG_DAMAGE 50
#define CG_50AE_DAMAGE 70

///---RIFLE AMMO---///

#define CG_545CAL_DAMAGE 30

#define CG_556CAL_DAMAGE 30
#define CG_556CAL_INCENDIARY_DAMAGE 32

#define CG_762CAL_DAMAGE 55
#define CG_762CAL_INCENDIARY_DAMAGE 50
#define CG_50BMG_DAMAGE 120

#define CG_75CAL_DAMAGE 150

///--SHOTGUN STUFF---///

#define CG_12G_SLUG_DAMAGE 80
#define CG_12G_INCAP_DAMAGE 15
#define CG_12G_PELLET_DAMAGE 9
#define CG_12G_DRAGONSBREATH_DAMAGE 6

///---UNIQUE WEAPONS---///

#define CG_BOLT_DAMAGE 45

/////---WOUNDING BONUSES---/////

#define CG_WOUND_MALUS -5
#define CG_LOWCAL_BONUS 0
#define CG_MEDCAL_BONUS 10
#define CG_HICAL_BONUS 20
#define CG_SHOTGUN_BONUS 5 // Per Pellet after all
#define CG_XTRM_WOUND_BONUS 30

////---ARMOR PIERCE---////

#define CG_NO_AP 0
#define CG_LOW_AP 5
#define CG_MED_AP 15
#define CG_HIGH_AP 25
#define CG_XTRM_AP 50



